### ISSUE TITLE
字体名称翻译

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/tex-by-topic-cn#2]
这里将 Computer Modern 翻译为了“计算机现代”，感觉不很妥当。保留原文我觉得并没有大碍。相应的还有 Computer Modern Roman 等，也可以不翻译。

**Comment by Liam0205** [comment]
赞同，今后的翻译会注意这一点。

先前的翻译，若有可能，欢迎提 PR~不然就得等校对的时候来搞了。
